### ISSUE TITLE
improper class parameter reference?

### ISSUE THREAD

**Issue by aidan1221** [pdx-cs-ai/gothello-libclient-python3#1]
Looks like on line 141-142 of gthclient.py, the variables white_time_control and black_time_control should be referencing the class parameters with self.white_time_control and self.black_time_control

**Comment by BartMassey** [comment]
Yeah, I've fixed this, but am now debugging the rest of the time control bugs.  Give me a bit.

Thanks much for the report!

**Comment by BartMassey** [comment]
Seems to work now. Haven't tested it carefully. Let me know if there's more bugs.
